# Generated by Django 5.1.4

import inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='preview_token',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='预览凭证'),
        ),
        migrations.CreateModel(
            name='PreviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=inspection.models.new_preview_code, max_length=40, unique=True, verbose_name='凭证编号')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消耗时间')),
                ('canceled', models.BooleanField(default=False, verbose_name='已取消')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
